### PR TITLE
Related object's fields in match_on

### PR DESCRIPTION
**Pull request by gregoriopellegrino**
Now it is possible to use related object's fields (=>) in the match_on column

### CODE REVIEW

**Comment by gregoriopellegrino** [comment]
fixe issue #9

**Comment by andrewdodd** [comment]
Hey,

I agree with the change of the '=>' to the '__', but that is a separate issue (and probably a separate PR) to the other change here.

**Comment by gregoriopellegrino** [comment]
Yes it is a separate issue. It was the issue #8 

Gregorio

**Comment by andrewdodd** [comment]
Ah, ok.

Would it be possible for you to:
 1. Create separate PRs for the #8 and #9 fixes
 2. Create tests for them?
 3. Make sure you don't break any other tests (unless they should change, in which case fix them?)?

Thanks,
Andrew

PS: I will definitely also spend some time on #9 this week (i was away last week).

**Pull request closed without merging**
